In [ ]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import keras
from keras.models import Sequential
from keras.layers import Dense
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split

:

In [2]:
data = pd.read_csv('heart.csv')
data.head()

,age,sex,chest_pain_type,Resting_Blood_Pressure,Serum_Cholestrol,Diabetes,restecg,thalach,exang,oldpeak,slope,ca,thalassemia,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [3]:
data.describe()

,age,sex,chest_pain_type,Resting_Blood_Pressure,Serum_Cholestrol,Diabetes,restecg,thalach,exang,oldpeak,slope,ca,thalassemia,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [4]:
data['ID'] = data.index  # Add an ID column
# Rearrange columns to place ID as the first column
cols = ['ID'] + [col for col in data.columns if col != 'ID']
data = data[cols]

In [5]:
data.head()

,ID,age,sex,chest_pain_type,Resting_Blood_Pressure,Serum_Cholestrol,Diabetes,restecg,thalach,exang,oldpeak,slope,ca,thalassemia,target
0,0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [6]:
data.isnull().any()

ID                        False
age                       False
sex                       False
chest_pain_type           False
Resting_Blood_Pressure    False
Serum_Cholestrol          False
Diabetes                  False
restecg                   False
thalach                   False
exang                     False
oldpeak                   False
slope                     False
ca                        False
thalassemia               False
target                    False
dtype: bool

In [7]:
X = data.iloc[:, 1:-1].values 
y = data["target"].values

In [31]:
X_train, X_test, y_train, y_test, ids_train, ids_test = train_test_split(X, y, data['ID'], test_size=0.2, random_state=0)

In [33]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [35]:
classifier = Sequential()
classifier.add(Dense(activation = "relu", input_dim = 13,
					units = 8, kernel_initializer = "uniform"))
classifier.add(Dense(activation = "relu", units = 14,
					kernel_initializer = "uniform"))
classifier.add(Dense(activation = "sigmoid", units = 1,
					kernel_initializer = "uniform"))
classifier.compile(optimizer = 'adam' , loss = 'binary_crossentropy',
				metrics = ['accuracy'] )

In [37]:
classifier.fit(X_train , y_train , batch_size = 8 ,epochs = 100 )

Epoch 1/100
31/31 [==============================] - 0s 1ms/step - loss: 0.2505 - accuracy: 0.9132
Epoch 2/100
31/31 [==============================] - 0s 1ms/step - loss: 0.2500 - accuracy: 0.9132
Epoch 3/100
31/31 [==============================] - 0s 1ms/step - loss: 0.2494 - accuracy: 0.9091
Epoch 4/100
31/31 [==============================] - 0s 1ms/step - loss: 0.2482 - accuracy: 0.9091
Epoch 5/100
31/31 [==============================] - 0s 2ms/step - loss: 0.2482 - accuracy: 0.9091
Epoch 6/100
31/31 [==============================] - 0s 3ms/step - loss: 0.2476 - accuracy: 0.9091
Epoch 7/100
31/31 [==============================] - 0s 1ms/step - loss: 0.2455 - accuracy: 0.9132
Epoch 8/100
31/31 [==============================] - 0s 1ms/step - loss: 0.2448 - accuracy: 0.9132
Epoch 9/100
31/31 [==============================] - 0s 1ms/step - loss: 0.2452 - accuracy: 0.9132
Epoch 10/100
31/31 [==============================] - 0s 1ms/step - loss: 0.2435 - accuracy: 0.9132
Epoch 11/100
31/31 [==============================] - 0s 1ms/step - loss: 0.2450 - accuracy: 0.9091
Epoch 12/100
31/31 [==============================] - 0s 1ms/step - loss: 0.2429 - accuracy: 0.9132
Epoch 13/100
31/31 [==============================] - 0s 2ms/step - loss: 0.2425 - accuracy: 0.9091
Epoch 14/100
31/31 [==============================] - 0s 2ms/step - loss: 0.2405 - accuracy: 0.9132
Epoch 15/100
31/31 [==============================] - 0s 2ms/step - loss: 0.2398 - accuracy: 0.9132
Epoch 16/100
31/31 [==============================] - 0s 2ms/step - loss: 0.2399 - accuracy: 0.9132
Epoch 17/100
31/31 [==============================] - 0s 2ms/step - loss: 0.2401 - accuracy: 0.9091
Epoch 18/100
31/31 [==============================] - 0s 2ms/step - loss: 0.2379 - accuracy: 0.9174
Epoch 19/100
31/31 [==============================] - 0s 1ms/step - loss: 0.2382 - accuracy: 0.9091
Epoch 20/100
31/31 [==============================] - 0s 2ms/step - loss: 0.2377 - accuracy: 0.9174
Epoch 21/100
31/31 [==============================] - 0s 1ms/step - loss: 0.2355 - accuracy: 0.9174
Epoch 22/100
31/31 [==============================] - 0s 1ms/step - loss: 0.2368 - accuracy: 0.9132
Epoch 23/100
31/31 [==============================] - 0s 2ms/step - loss: 0.2341 - accuracy: 0.9174
Epoch 24/100
31/31 [==============================] - 0s 2ms/step - loss: 0.2333 - accuracy: 0.9050
Epoch 25/100
31/31 [==============================] - 0s 2ms/step - loss: 0.2317 - accuracy: 0.9174
Epoch 26/100
31/31 [==============================] - 0s 1ms/step - loss: 0.2306 - accuracy: 0.9132
Epoch 27/100
31/31 [==============================] - 0s 2ms/step - loss: 0.2294 - accuracy: 0.9132
Epoch 28/100
31/31 [==============================] - 0s 1ms/step - loss: 0.2281 - accuracy: 0.9132
Epoch 29/100
31/31 [==============================] - 0s 2ms/step - loss: 0.2278 - accuracy: 0.9132
Epoch 30/100
31/31 [==============================] - 0s 2ms/step - loss: 0.2258 - accuracy: 0.9132
Epoch 31/100
31/31 [==============================] - 0s 3ms/step - loss: 0.2247 - accuracy: 0.9174
Epoch 32/100
31/31 [==============================] - 0s 1ms/step - loss: 0.2238 - accuracy: 0.9174
Epoch 33/100
31/31 [==============================] - 0s 1ms/step - loss: 0.2231 - accuracy: 0.9174
Epoch 34/100
31/31 [==============================] - 0s 1ms/step - loss: 0.2226 - accuracy: 0.9174
Epoch 35/100
31/31 [==============================] - 0s 1ms/step - loss: 0.2212 - accuracy: 0.9174
Epoch 36/100
31/31 [==============================] - 0s 1ms/step - loss: 0.2215 - accuracy: 0.9174
Epoch 37/100
31/31 [==============================] - 0s 1ms/step - loss: 0.2203 - accuracy: 0.9174
Epoch 38/100
31/31 [==============================] - 0s 1ms/step - loss: 0.2186 - accuracy: 0.9215
Epoch 39/100
31/31 [==============================] - 0s 1ms/step - loss: 0.2175 - accuracy: 0.9174
Epoch 40/100
31/31 [==============================] - 0s 1ms/step - loss: 0.2175 - accuracy: 0.9174
Epoch 41/100
31/31 [==============================] - 0s 1ms/step - loss: 0.2152 - accuracy: 0.9174
Epoch 42/100
31/31 [==============================] - 0s 1ms/step - loss: 0.2143 - accuracy: 0.9174
Epoch 43/100
31/31 [==============================] - 0s 1ms/step - loss: 0.2137 - accuracy: 0.9174
Epoch 44/100
31/31 [==============================] - 0s 1ms/step - loss: 0.2147 - accuracy: 0.9215
Epoch 45/100
31/31 [==============================] - 0s 1ms/step - loss: 0.2135 - accuracy: 0.9174
Epoch 46/100
31/31 [==============================] - 0s 1ms/step - loss: 0.2122 - accuracy: 0.9174
Epoch 47/100
31/31 [==============================] - 0s 1ms/step - loss: 0.2115 - accuracy: 0.9174
Epoch 48/100
31/31 [==============================] - 0s 1ms/step - loss: 0.2139 - accuracy: 0.9215
Epoch 49/100
31/31 [==============================] - 0s 1ms/step - loss: 0.2086 - accuracy: 0.9174
Epoch 50/100
31/31 [==============================] - 0s 1ms/step - loss: 0.2075 - accuracy: 0.9174
Epoch 51/100
31/31 [==============================] - 0s 1ms/step - loss: 0.2079 - accuracy: 0.9174
Epoch 52/100
31/31 [==============================] - 0s 1ms/step - loss: 0.2073 - accuracy: 0.9215
Epoch 53/100
31/31 [==============================] - 0s 1ms/step - loss: 0.2074 - accuracy: 0.9215
Epoch 54/100
31/31 [==============================] - 0s 1ms/step - loss: 0.2066 - accuracy: 0.9215
Epoch 55/100
31/31 [==============================] - 0s 2ms/step - loss: 0.2061 - accuracy: 0.9215
Epoch 56/100
31/31 [==============================] - 0s 1ms/step - loss: 0.2043 - accuracy: 0.9215
Epoch 57/100
31/31 [==============================] - 0s 1ms/step - loss: 0.2042 - accuracy: 0.9215
Epoch 58/100
31/31 [==============================] - 0s 1ms/step - loss: 0.2025 - accuracy: 0.9256
Epoch 59/100
31/31 [==============================] - 0s 1ms/step - loss: 0.2024 - accuracy: 0.9215
Epoch 60/100
31/31 [==============================] - 0s 1ms/step - loss: 0.2032 - accuracy: 0.9256
Epoch 61/100
31/31 [==============================] - 0s 1ms/step - loss: 0.2000 - accuracy: 0.9215
Epoch 62/100
31/31 [==============================] - 0s 1ms/step - loss: 0.2005 - accuracy: 0.9256
Epoch 63/100
31/31 [==============================] - 0s 1ms/step - loss: 0.2001 - accuracy: 0.9256
Epoch 64/100
31/31 [==============================] - 0s 1ms/step - loss: 0.1991 - accuracy: 0.9215
Epoch 65/100
31/31 [==============================] - 0s 1ms/step - loss: 0.1987 - accuracy: 0.9215
Epoch 66/100
31/31 [==============================] - 0s 1ms/step - loss: 0.1970 - accuracy: 0.9256
Epoch 67/100
31/31 [==============================] - 0s 1ms/step - loss: 0.1962 - accuracy: 0.9256
Epoch 68/100
31/31 [==============================] - 0s 1ms/step - loss: 0.1950 - accuracy: 0.9256
Epoch 69/100
31/31 [==============================] - 0s 2ms/step - loss: 0.1953 - accuracy: 0.9298
Epoch 70/100
31/31 [==============================] - 0s 2ms/step - loss: 0.1953 - accuracy: 0.9256
Epoch 71/100
31/31 [==============================] - 0s 2ms/step - loss: 0.1926 - accuracy: 0.9298
Epoch 72/100
31/31 [==============================] - 0s 2ms/step - loss: 0.1926 - accuracy: 0.9298
Epoch 73/100
31/31 [==============================] - 0s 2ms/step - loss: 0.1913 - accuracy: 0.9298
Epoch 74/100
31/31 [==============================] - 0s 2ms/step - loss: 0.1918 - accuracy: 0.9256
Epoch 75/100
31/31 [==============================] - 0s 2ms/step - loss: 0.1902 - accuracy: 0.9256
Epoch 76/100
31/31 [==============================] - 0s 2ms/step - loss: 0.1936 - accuracy: 0.9339
Epoch 77/100
31/31 [==============================] - 0s 2ms/step - loss: 0.1945 - accuracy: 0.9256
Epoch 78/100
31/31 [==============================] - 0s 2ms/step - loss: 0.1893 - accuracy: 0.9256
Epoch 79/100
31/31 [==============================] - 0s 2ms/step - loss: 0.1867 - accuracy: 0.9339
Epoch 80/100
31/31 [==============================] - 0s 2ms/step - loss: 0.1880 - accuracy: 0.9339
Epoch 81/100
31/31 [==============================] - 0s 2ms/step - loss: 0.1846 - accuracy: 0.9380
Epoch 82/100
31/31 [==============================] - 0s 1ms/step - loss: 0.1841 - accuracy: 0.9339
Epoch 83/100
31/31 [==============================] - 0s 2ms/step - loss: 0.1829 - accuracy: 0.9380
Epoch 84/100
31/31 [==============================] - 0s 1ms/step - loss: 0.1831 - accuracy: 0.9339
Epoch 85/100
31/31 [==============================] - 0s 1ms/step - loss: 0.1853 - accuracy: 0.9339
Epoch 86/100
31/31 [==============================] - 0s 2ms/step - loss: 0.1840 - accuracy: 0.9339
Epoch 87/100
31/31 [==============================] - 0s 2ms/step - loss: 0.1811 - accuracy: 0.9339
Epoch 88/100
31/31 [==============================] - 0s 2ms/step - loss: 0.1829 - accuracy: 0.9339
Epoch 89/100
31/31 [==============================] - 0s 2ms/step - loss: 0.1799 - accuracy: 0.9380
Epoch 90/100
31/31 [==============================] - 0s 1ms/step - loss: 0.1779 - accuracy: 0.9380
Epoch 91/100
31/31 [==============================] - 0s 1ms/step - loss: 0.1804 - accuracy: 0.9421
Epoch 92/100
31/31 [==============================] - 0s 1ms/step - loss: 0.1791 - accuracy: 0.9421
Epoch 93/100
31/31 [==============================] - 0s 1ms/step - loss: 0.1776 - accuracy: 0.9380
Epoch 94/100
31/31 [==============================] - 0s 2ms/step - loss: 0.1768 - accuracy: 0.9339
Epoch 95/100
31/31 [==============================] - 0s 2ms/step - loss: 0.1771 - accuracy: 0.9380
Epoch 96/100
31/31 [==============================] - 0s 1ms/step - loss: 0.1757 - accuracy: 0.9380
Epoch 97/100
31/31 [==============================] - 0s 1ms/step - loss: 0.1743 - accuracy: 0.9380
Epoch 98/100
31/31 [==============================] - 0s 1ms/step - loss: 0.1735 - accuracy: 0.9380
Epoch 99/100
31/31 [==============================] - 0s 2ms/step - loss: 0.1734 - accuracy: 0.9380
Epoch 100/100
31/31 [==============================] - 0s 1ms/step - loss: 0.1752 - accuracy: 0.9380

In [38]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

2/2 [==============================] - 0s 2ms/step

In [39]:
predictions_df = pd.DataFrame({
    'ID': ids_test,
    'Actual': y_test,
    'Predicted': y_pred.flatten()
})

In [43]:
print("Predictions:\n", predictions_df)

Predictions:
       ID  Actual  Predicted
225  225       0      False
152  152       1       True
228  228       0       True
201  201       0      False
52    52       1      False
..   ...     ...        ...
146  146       1       True
302  302       0       True
26    26       1       True
108  108       1       True
89    89       1       True

[61 rows x 3 columns]

In [44]:
cm = confusion_matrix(y_test,y_pred)
cm

array([[24,  3],
       [ 3, 31]], dtype=int64)

In [45]:
accuracy = (cm[0][0]+cm[1][1])/(cm[0][1] + cm[1][0] +cm[0][0] +cm[1][1])
print(accuracy*100)

90.1639344262295